name: diaguia
description: "Guía de consulta para usuarios de bombas de insulina y sensores de glucosa."
publish_to: 'none'

version: 2.0.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.5
  wakelock_plus: ^1.7.0
  flutter_local_notifications: ^22.3.0
  timezone: ^0.11.1
  url_launcher: ^6.3.2
  package_info_plus: ^10.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
