name: Flutter CI/CD (APK & Web)

on:
  push:
    branches:
      - main
      - dev
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      # 1. Preparación inicial
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.x'

      - name: Install dependencies
        run: flutter pub get

      # 2. Compilación 
      - name: Build APK
        run: flutter build apk --release

      - name: Build Web
        run: flutter build web --base-href "/${{ github.event.repository.name }}/"

      # 3. Instalación de GH CLI
      - name: Install GitHub CLI
        run: sudo apt-get update && sudo apt-get install -y gh

      # 4. Gestión de Release (APK)
      - name: Manage Release Assets
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          RELEASE="latest"
          APK_PATH="build/app/outputs/flutter-apk/app-release.apk"
          NEW_NAME="build/app/outputs/flutter-apk/app-release-latest.apk"
          
          # Renombramos localmente antes de subir
          mv $APK_PATH $NEW_NAME

          # Crear la release si no existe (el '|| true' evita que el script se pare si ya existe)
          gh release create $RELEASE --title "Latest Release" --notes "Automated Flutter build" || true

          # Subir el APK. --clobber sobrescribe el archivo si ya existe en la release
          gh release upload $RELEASE $NEW_NAME --clobber

      # 5. Despliegue Web a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web